name: Build and Push Docker Image to Docker Hub

# 控制工作流何时运行
on:
  # 当推送到 main 分支时触发
  push:
    branches: [ "main" ] # 或者你的主分支名称，如 master
  # 允许你从 Actions 标签页手动运行此工作流
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest # 使用 GitHub 提供的最新 Ubuntu 运行器

    steps:
      # 步骤 1: 检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4 # 使用官方的 checkout action

      # 步骤 2: 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 使用你设置的 Secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # 使用你设置的 Secret

      # 步骤 3: 构建 Docker 镜像并推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Docker 构建上下文路径 (仓库根目录)
          file: ./Dockerfile # Dockerfile 的路径 (相对于 context)
          push: true # 设置为 true 以推送镜像
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/corl:latest # 镜像标签，格式: <用户名>/<仓库名>:<标签>
          # 你可以添加更多标签，例如基于 Git commit SHA 的标签：
          # tags: |
          #   ${{ secrets.DOCKERHUB_USERNAME }}/corl:latest
          #   ${{ secrets.DOCKERHUB_USERNAME }}/corl:${{ github.sha }}
